READY: Full translation cryptography/crypto-ctfs-tricks.md
yurahod/UA-hacktricks pull request #18
Opened 2024-02-27 20:51 UTC by yurahod

READY: Full translation cryptography/crypto-ctfs-tricks.md

2024-03-03 18:04 UTC, Nz1Yv requested changes

2024-03-03 18:04 UTC, Nz1Yv commented on cryptography/crypto-ctfs-tricks.md
> +**Raw Deflate** та **Raw Inflate** (обидва можна знайти в Cyberchef) можуть стискати та розстискати дані без заголовків.
розпаковувати ?

2024-03-06 21:54 UTC, yurahod commented on cryptography/crypto-ctfs-tricks.md
> +Літера в число за формулою `(ax+b)%26` (де _a_ і _b_ - ключі, а _x_ - літера), і результат назад у літеру.
ааааа боже...

2024-03-06 21:55 UTC, yurahod commented on cryptography/crypto-ctfs-tricks.md
> +**Raw Deflate** та **Raw Inflate** (обидва можна знайти в Cyberchef) можуть стискати та розстискати дані без заголовків.
думав над розтисканням і розпаковуванням) обидва звучать якось дивно
Розпакувати можна архів файлів, але хз як щодо даних

2024-03-16 17:10 UTC, Nz1Yv approved these changes

2024-03-18 14:59 UTC, merged